### ISSUE TITLE
Invalid `:after .header` selector

### ISSUE THREAD

**Issue by devmao** [Semantic-Org/Semantic-UI-CSS#83]
I think this is a not valid selector. Also, `Parcel` emits an error when processing the Semantic-UI CSS on that line:

```css
[data-tooltip][data-inverted]:after .header {
  background-color: none;
  color: #FFFFFF;
} 

/*--------------
    Position
---------------*/
```
